// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeModeEnabled': string;
  'buttons': string;
  'desktopContainer': string;
  'singleCharacterButton': string;
}
export const cssExports: CssExports;
export default cssExports;
