// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addNew': string;
  'binaryWeights': string;
  'classIcon': string;
  'customStatEditor': string;
  'customStatView': string;
  'customStatsSettings': string;
  'identifiyingInfo': string;
  'inputlike': string;
  'label': string;
  'nonZero': string;
  'plus': string;
  'statWeightRow': string;
  'zero': string;
}
export const cssExports: CssExports;
export default cssExports;
